module.exports = {
  name: 'Name is required',
  link: 'Link is required',
  owner: 'Owner is required',
  avatar: 'Avatar is required',
  email: 'Email is required',
  emailExist: 'Email already exist',
  emailFormat: 'Wrong email format',
  urlFormat: 'Wrong url format',
  password: 'Password is required',
  strongPasswordFormat: 'Password is not strong',
  credentials: 'Wrong email or password',
  minLength: 'Min length have to be',
  maxLength: 'Man length have to be',
  type: 'Wrong type',
  ref: 'Wrong ref',
  unauthorized: 'You have to be authorized',
  notEnoughRight: 'You dont have enough rights',
  pageNotFound: 'Page not found',
};
